apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalrredis-deployment
  labels:
    app: signalrredis
spec:
  replicas: 10
  selector:
    matchLabels:
      app: signalrredis
  template:
    metadata:
      labels:
        app: signalrredis
    spec:
      containers:
      - name: signalrredis
        image: ashwin027/signalrredis:latest
        env:
        - name: RedisConfig__UseAsBackplane
          value: "false"
        - name: RedisConfig__Settings__Host
          value: "SET_REDIS_HOST_URL_HERE"
        - name: RedisConfig__Settings__Password
          valueFrom:
            secretKeyRef:
              name: redispassword
              key: redispassword
        - name: PodName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80