apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: signalrredis-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - host: signalrredis.local
    http:
      paths:
      - backend:
          serviceName: signalrredis-service
          servicePort: 80
        path: /